export enum LOAN_STATUS_ENUM {
  INITIAL = "INITIATED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum OFFER_STATUS_ENUM {
  ISSUED = "ISSUED",
  BORROWER_ACCEPTED = "BORROWER_ACCEPTED",
  BORROWER_REJECTED = "BORROWER_REJECTED",
  LENDER_REJECTED = "LENDER_REJECTED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}

export enum LENDER_DASHBOARD_SUMMARY_TYPE_ENUM {
  OFFER_SENT = "offerSent",
  OFFER_ACCEPTED = "offerAccepted",
  OFFER_REJECTED = "offerRejected",
  OFFER_DISBURSED = "offerDisbursed",
}
