export enum LOAN_STATUS_ENUM {
  INITIAL = "INITIATED",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
}

export enum OFFER_STATUS_ENUM {
  ISSUED = "ISSUED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}

export enum LENDER_DASHBOARD_SUMMARY_TYPE_ENUM {
  OFFER_SENT = "offerSent",
  OFFER_ACCEPTED = "offerAccepted",
  OFFER_REJECTED = "offerRejected",
  OFFER_DISBURSED = "offerDisbursed",
}
